/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Artifact from './Artifact';
import Pagination from './Pagination';

/**
 * The ArtifactList model module.
 * @module model/ArtifactList
 * @version 1.0.0
 */
class ArtifactList {
    /**
     * Constructs a new <code>ArtifactList</code>.
     * @alias module:model/ArtifactList
     */
    constructor() { 
        
        ArtifactList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ArtifactList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArtifactList} obj Optional instance to populate.
     * @return {module:model/ArtifactList} The populated <code>ArtifactList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArtifactList();

            if (data.hasOwnProperty('artifacts')) {
                obj['artifacts'] = ApiClient.convertToType(data['artifacts'], [Artifact]);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = Pagination.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Artifact>} artifacts
 */
ArtifactList.prototype['artifacts'] = undefined;

/**
 * @member {module:model/Pagination} pagination
 */
ArtifactList.prototype['pagination'] = undefined;






export default ArtifactList;

