/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Health model module.
 * @module model/Health
 * @version 1.0.0
 */
class Health {
    /**
     * Constructs a new <code>Health</code>.
     * @alias module:model/Health
     */
    constructor() { 
        
        Health.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Health</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Health} obj Optional instance to populate.
     * @return {module:model/Health} The populated <code>Health</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Health();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The status of the database, one of \"OK\", \"Error\", \"Pending\"
 * @member {String} status
 */
Health.prototype['status'] = undefined;

/**
 * A message to explain the current status
 * @member {String} message
 */
Health.prototype['message'] = undefined;






export default Health;

