/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject model module.
 * @module model/InlineObject
 * @version 0.1
 */
class InlineObject {
    /**
     * Constructs a new <code>InlineObject</code>.
     * @alias module:model/InlineObject
     * @param resultId {String} ID of result to attach artifact to
     * @param filename {String} ID of pet to update
     * @param file {File} file to upload
     */
    constructor(resultId, filename, file) { 
        
        InlineObject.initialize(this, resultId, filename, file);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, resultId, filename, file) { 
        obj['resultId'] = resultId;
        obj['filename'] = filename;
        obj['file'] = file;
    }

    /**
     * Constructs a <code>InlineObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject} obj Optional instance to populate.
     * @return {module:model/InlineObject} The populated <code>InlineObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject();

            if (data.hasOwnProperty('resultId')) {
                obj['resultId'] = ApiClient.convertToType(data['resultId'], 'String');
            }
            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = ApiClient.convertToType(data['file'], File);
            }
            if (data.hasOwnProperty('additionalMetadata')) {
                obj['additionalMetadata'] = ApiClient.convertToType(data['additionalMetadata'], Object);
            }
        }
        return obj;
    }


}

/**
 * ID of result to attach artifact to
 * @member {String} resultId
 */
InlineObject.prototype['resultId'] = undefined;

/**
 * ID of pet to update
 * @member {String} filename
 */
InlineObject.prototype['filename'] = undefined;

/**
 * file to upload
 * @member {File} file
 */
InlineObject.prototype['file'] = undefined;

/**
 * Additional data to pass to server
 * @member {Object} additionalMetadata
 */
InlineObject.prototype['additionalMetadata'] = undefined;






export default InlineObject;

