/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReportParameters from './ReportParameters';

/**
 * The Report model module.
 * @module model/Report
 * @version 0.1
 */
class Report {
    /**
     * Constructs a new <code>Report</code>.
     * @alias module:model/Report
     */
    constructor() { 
        
        Report.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Report</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Report} obj Optional instance to populate.
     * @return {module:model/Report} The populated <code>Report</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Report();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
            if (data.hasOwnProperty('mimetype')) {
                obj['mimetype'] = ApiClient.convertToType(data['mimetype'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('download_url')) {
                obj['download_url'] = ApiClient.convertToType(data['download_url'], 'String');
            }
            if (data.hasOwnProperty('view_url')) {
                obj['view_url'] = ApiClient.convertToType(data['view_url'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ReportParameters.constructFromObject(data['parameters']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Unique ID of the project
 * @member {String} id
 */
Report.prototype['id'] = undefined;

/**
 * The filename of the report
 * @member {String} filename
 */
Report.prototype['filename'] = undefined;

/**
 * The mime type of the downloadable file
 * @member {String} mimetype
 */
Report.prototype['mimetype'] = undefined;

/**
 * The URL to the downloadable report (deprecated)
 * @member {String} url
 */
Report.prototype['url'] = undefined;

/**
 * The URL to the downloadable report
 * @member {String} download_url
 */
Report.prototype['download_url'] = undefined;

/**
 * The URL to the viewable report
 * @member {String} view_url
 */
Report.prototype['view_url'] = undefined;

/**
 * @member {module:model/ReportParameters} parameters
 */
Report.prototype['parameters'] = undefined;

/**
 * The status of the report, one of \"pending\", \"running\", \"done\"
 * @member {String} status
 */
Report.prototype['status'] = undefined;






export default Report;

