/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Pagination from './Pagination';
import Report from './Report';

/**
 * The ReportList model module.
 * @module model/ReportList
 * @version 0.1
 */
class ReportList {
    /**
     * Constructs a new <code>ReportList</code>.
     * @alias module:model/ReportList
     */
    constructor() { 
        
        ReportList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportList} obj Optional instance to populate.
     * @return {module:model/ReportList} The populated <code>ReportList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportList();

            if (data.hasOwnProperty('reports')) {
                obj['reports'] = ApiClient.convertToType(data['reports'], [Report]);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = Pagination.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Report>} reports
 */
ReportList.prototype['reports'] = undefined;

/**
 * @member {module:model/Pagination} pagination
 */
ReportList.prototype['pagination'] = undefined;






export default ReportList;

