/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Pagination from './Pagination';
import Result from './Result';

/**
 * The ResultList model module.
 * @module model/ResultList
 * @version 0.1
 */
class ResultList {
    /**
     * Constructs a new <code>ResultList</code>.
     * @alias module:model/ResultList
     */
    constructor() { 
        
        ResultList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResultList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResultList} obj Optional instance to populate.
     * @return {module:model/ResultList} The populated <code>ResultList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResultList();

            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [Result]);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = Pagination.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Result>} results
 */
ResultList.prototype['results'] = undefined;

/**
 * @member {module:model/Pagination} pagination
 */
ResultList.prototype['pagination'] = undefined;






export default ResultList;

