/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Pagination from './Pagination';
import Run from './Run';

/**
 * The RunList model module.
 * @module model/RunList
 * @version 1.0.0
 */
class RunList {
    /**
     * Constructs a new <code>RunList</code>.
     * @alias module:model/RunList
     */
    constructor() { 
        
        RunList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RunList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RunList} obj Optional instance to populate.
     * @return {module:model/RunList} The populated <code>RunList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RunList();

            if (data.hasOwnProperty('runs')) {
                obj['runs'] = ApiClient.convertToType(data['runs'], [Run]);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = Pagination.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Run>} runs
 */
RunList.prototype['runs'] = undefined;

/**
 * @member {module:model/Pagination} pagination
 */
RunList.prototype['pagination'] = undefined;






export default RunList;

