/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WidgetParam model module.
 * @module model/WidgetParam
 * @version 0.1
 */
class WidgetParam {
    /**
     * Constructs a new <code>WidgetParam</code>.
     * @alias module:model/WidgetParam
     */
    constructor() { 
        
        WidgetParam.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WidgetParam</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WidgetParam} obj Optional instance to populate.
     * @return {module:model/WidgetParam} The populated <code>WidgetParam</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WidgetParam();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The name of the parameter to supply to the widget
 * @member {String} name
 */
WidgetParam.prototype['name'] = undefined;

/**
 * A friendly description of the parameter
 * @member {String} description
 */
WidgetParam.prototype['description'] = undefined;

/**
 * The type of parameter (string, integer, etc)
 * @member {String} type
 */
WidgetParam.prototype['type'] = undefined;






export default WidgetParam;

