/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Pagination from './Pagination';
import WidgetType from './WidgetType';

/**
 * The WidgetTypeList model module.
 * @module model/WidgetTypeList
 * @version 1.0.0
 */
class WidgetTypeList {
    /**
     * Constructs a new <code>WidgetTypeList</code>.
     * @alias module:model/WidgetTypeList
     */
    constructor() { 
        
        WidgetTypeList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WidgetTypeList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WidgetTypeList} obj Optional instance to populate.
     * @return {module:model/WidgetTypeList} The populated <code>WidgetTypeList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WidgetTypeList();

            if (data.hasOwnProperty('types')) {
                obj['types'] = ApiClient.convertToType(data['types'], [WidgetType]);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = Pagination.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/WidgetType>} types
 */
WidgetTypeList.prototype['types'] = undefined;

/**
 * @member {module:model/Pagination} pagination
 */
WidgetTypeList.prototype['pagination'] = undefined;






export default WidgetTypeList;

