/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@IbutsuClient);
  }
}(this, function(expect, @IbutsuClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @IbutsuClient.ArtifactApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ArtifactApi', function() {
    describe('deleteArtifact', function() {
      it('should call deleteArtifact successfully', function(done) {
        //uncomment below and update the code to test deleteArtifact
        //instance.deleteArtifact(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('downloadArtifact', function() {
      it('should call downloadArtifact successfully', function(done) {
        //uncomment below and update the code to test downloadArtifact
        //instance.downloadArtifact(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArtifact', function() {
      it('should call getArtifact successfully', function(done) {
        //uncomment below and update the code to test getArtifact
        //instance.getArtifact(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArtifactList', function() {
      it('should call getArtifactList successfully', function(done) {
        //uncomment below and update the code to test getArtifactList
        //instance.getArtifactList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadArtifact', function() {
      it('should call uploadArtifact successfully', function(done) {
        //uncomment below and update the code to test uploadArtifact
        //instance.uploadArtifact(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('viewArtifact', function() {
      it('should call viewArtifact successfully', function(done) {
        //uncomment below and update the code to test viewArtifact
        //instance.viewArtifact(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
