/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@IbutsuClient);
  }
}(this, function(expect, @IbutsuClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @IbutsuClient.WidgetConfigApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WidgetConfigApi', function() {
    describe('addWidgetConfig', function() {
      it('should call addWidgetConfig successfully', function(done) {
        //uncomment below and update the code to test addWidgetConfig
        //instance.addWidgetConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteWidgetConfig', function() {
      it('should call deleteWidgetConfig successfully', function(done) {
        //uncomment below and update the code to test deleteWidgetConfig
        //instance.deleteWidgetConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgetConfig', function() {
      it('should call getWidgetConfig successfully', function(done) {
        //uncomment below and update the code to test getWidgetConfig
        //instance.getWidgetConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgetConfigList', function() {
      it('should call getWidgetConfigList successfully', function(done) {
        //uncomment below and update the code to test getWidgetConfigList
        //instance.getWidgetConfigList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateWidgetConfig', function() {
      it('should call updateWidgetConfig successfully', function(done) {
        //uncomment below and update the code to test updateWidgetConfig
        //instance.updateWidgetConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
